server:
  port: 8093

spring:
  main:
    banner-mode: off
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/best_commerce?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
      use_sql_comments: true
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Baku