language: java
jdk:
  - openjdk11

deploy:
  provider: heroku
  api_key:
    secure: "d0943ce3-47cc-44a0-9c64-c81ced226c3c"
  on:
    all_branches: true 
  skip_cleanup: true  
      
notification:
  email: kamilhumbatov@gmail.com
