version: '3.7'

services:

  db:
    image: mysql:5.7
    container_name: mysql
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_DATABASE: best_commerce
      MYSQL_USER: commerce
      MYSQL_PASSWORD: 123
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backend

  exam1:
    build: ./exam1
    depends_on:
      - db
    networks:
      - backend
    ports:
      - "8092:8092"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/best_commerce?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: commerce
      SPRING_DATASOURCE_PASSWORD: 123


volumes:
  db-data:

networks:
  backend:
  back:
    driver: bridge