server:
  port: 8095

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: summodern
    password: k10091984
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
  kafka:
    topic:
      name: commerceTopic
    producer:
      bootstrap-servers: ${KAFKA_HOST_NAME:kafka}:9092
      properties:
        retry.backoff.ms: 1000
    admin:
      properties:
        bootstrap.servers: ${KAFKA_HOST_NAME:kafka}:9092
    consumer:
      bootstrap-servers: ${KAFKA_HOST_NAME:kafka}:${KAFKA_PORT:9092}
      group-id: notification-group-id