server:
  port: 8092

spring:
  main:
    banner-mode: off
  datasource:
    url: jdbc:mysql://${DATABASE_HOST:localhost}:${DATABASE_PORT:3306}/best_commerce_product?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
    username: ${DATABASE_USER:root}
    password: ${DATABASE_PASSWORD:root}
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
      use_sql_comments: true
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Baku
    cache:
      type: redis
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}

security:
  jwtProperties:
       secret: n2r5u8x/A%D*G-KaPdSgVkYp3s6v9y$B&E(H+MbQeThWmZq4t7w!z%C*F-J@NcRf
       token-validity: 43200000
       token-validity-for-remember-me: 43200000