server:
  port: 8093

spring:
  main:
    banner-mode: off
  datasource:
    url: jdbc:mysql://${DATABASE_HOST:localhost}:${DATABASE_PORT:3306}/best_commerce?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
    username: ${DATABASE_USER:root}
    password: ${DATABASE_PASSWORD:root}
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none
      use_sql_comments: true
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Baku
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
  kafka:
    topic:
      name: commerceTopic
    producer:
      bootstrap-servers: ${KAFKA_HOST_NAME:localhost}:9092
      properties:
        retry.backoff.ms: 1000
security:
  jwtProperties:
       secret: n2r5u8x/A%D*G-KaPdSgVkYp3s6v9y$B&E(H+MbQeThWmZq4t7w!z%C*F-J@NcRf
       token-validity: 43200000
       token-validity-for-remember-me: 604800000