server:
  port: 8092

spring:
  main:
    banner-mode: off
  datasource:
    url: jdbc:mysql://${DATABASE_HOST:localhost}:${DATABASE_PORT:3306}/best_commerce?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
    username: ${DATABASE_USER:commerce}
    password: ${DATABASE_PASSWORD:123}
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
      use_sql_comments: true
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Baku

security:
  jwtProperties:
       secret: bestCommerce2020
       token-validity: 86400
       token-validity-for-remember-me: 604800